---
title: "Lab 2"
output: html_document
---

Индивидуальные задания на использование базовых функций R (без использования пакетов).
Краткое описание файлов, используемых в заданиях, дано ниже, после списка заданий.
Каждому студенту необходимо выполнить задание N и N+15, где N - номер студента. Таким образом, одно и то же задание могут выполнить не более 2х студентов.

***Задания***

1. Используйте файл ExpImp.Rdata
Напишите функцию, которая создает именованный список, такой что
 - именами элементов списка являются названия федеральных округов
 - элементами списка являются векторы, которые содержат те субъекты федерации, которые принадлежат соответствующему федеральному округу.
2. Используйте файл ExpImp.Rdata
Напишите функцию, в которой пользователь подает на вход название субъекта федерации или федерального округа и получает на выходе получает два списка: в первом списке названия тех отраслей промышленности, по которым экспорт превышает импорт, а во втором - названия тех отраслей промышленности, по которым импорт превышает экспорт.
3. Используйте файл ExpImp.Rdata
Создайте data.frame в котором содержится только информация по федеральным округам. Добавьте в него колонки, в которых содержится суммарный экспорт и импорт по федеральным округам. Напишите функцию, которая в полученном Вами data.frame находит федеральные округа, в которых суммарные экспорт превышает суммарный импорт.
4. Используйте файл ExpImp.Rdata
Создайте data.frame в котором содержится только информация по субъектам федерации. Добавьте в него колонки, в которых содержится суммарный экспорт и импорт по субъектам федерации. Напишите функцию, которая в полученном Вами data.frame находит субъекты федерации в которых суммарные экспорт превышает суммарный импорт.
5. Используйте файл ExpImp.Rdata
Преобразуйте data.frame так, чтобы данные по экспорту стояли вначале, а данные по импорту в конце. Добавьте в него колонки, в которых содержится суммарный экспорт и импорт. Напишите функцию, которая в полученном Вами data.frame находит субъекты федерации в которых суммарные экспорт превышает суммарный импорт.
6. Используйте файл ExpImp.Rdata
Напишите функцию, которая по названию федерального округа находит те субъекты федерации, которые принадлежат этому федеральному округу и в которых суммарный экспорт превышает суммарный импорт.
7. Используйте файл ExpImp.Rdata
Напишите функцию, которая по названию субъекта федерации выводит значения суммарного экспорта и суммарного импорта по этому субъекту федерации, а также федеральный округ, к которому этот субъект федерации относится.
8. Используйте файл RH_T.csv
Найдите самую жаркую неделю 2020 года в Екатеринбурге (Средняя температура в течение недели максимальна. Неполные недели в начале и в конце года не считаем.).
9. Используйте файл RH_T.csv
Найдите самые холодные выходные в Екатеринбурге (Средняя температура в течение выходных минимальна).
10. Используйте файл RH_T.csv
Найдите самую холодную среду и самый теплый четверг в Екатеринбурге.
11. Используйте файл RH_T.csv
Напишите функцию, которая находит 2 соседних дня с максимальным перепадом температуры.
12. Используйте файлы data2.csv, data1.txt
Объедините data.frames по идентификаторам сортов. Исключите те сорта, для которых есть пропущенные значения. Для качественных признаков найти медиану, для количественных – среднее значение.
13. Используйте файл Air_flows.txt
Напишите функцию, которая создает именованный список, в котором имена - это названия городов, значения – общее количество пассажиров прибывших в города. Напишите функцию, которая по названию города выводит список тех городов, в которые осуществляются перевозки из этого города.
14. Используйте файл Regions.csv
Напишите функцию, которая принимает на вход название региона и выдает список тех временных промежутков (год1-год2), когда в этом регионе наблюдался рост численности населения и список тех временных промежутков, когда в регионе наблюдалось падение численности населения.
15. Используйте файл outcome-of-care-measures.csv
Напишите функцию, которая принимает на вход название штата и выдает на выход список, который содержит количество больниц в штате и среднее количество людей умерших и вернувшихся в больницу в течение 30 дней, для каждого из трех заболеваний.
16. Используйте файл outcome-of-care-measures.csv
Напишите функцию, которая принимает на вход название города и допустимый диапазон смертности и выдает на выход список, в котором для каждого из трех заболеваний указаны названия тех больниц уровень смертности в которых не превышает указанный диапазон.
17. Используйте файл outcome-of-care-measures.csv
Напишите функцию, которая принимает на вход название штата и выдает на выход список, который содержит количество больниц в штате и максимальный и минимальный уровень смертности от каждого из трех заболеваний в больницах этого штата.
18. Используйте файл outcome-of-care-measures.csv
Напишите функцию, которая принимает на вход название штата и выдает на выход список, который содержит количество больниц в штате и максимальный и минимальный уровень смертности от каждого из трех заболеваний в больницах этого штата.
19. Используйте файл Payment_and_value_of_Care-Hospital.csv
Напишите функцию, которая на вход принимает название города и название медицинской процедуры/заболевания, а на выход выдает именованный список, в котором в качестве имен используется название больницы в которой можно получить медицинскую помощь, а качестве значений – усредненная стоимость услуги в данной больнице. Список должен быть упорядочен по возрастанию значения стоимости услуги.
20. Используйте файл Payment_and_value_of_Care-Hospital.csv
Напишите функцию, которая на вход принимает название Штата, название медицинской процедуры/заболевания и максимальную сумму которую пациент готов потратить на лечение ( в долларах). На выход функция должна выдавать список, в котором указаны название больницы, город и адрес больницы и диапазон стоимости необходимой услуги. Список должен быть упорядочен по возрастанию среднего значения стоимости услуги. Если на данную сумму невозможно получить данную услугу, то функция должна выдать сообщение, в котором указана минимальная стоимость услуги в штате.
21. Используйте файл Payment_and_value_of_Care-Hospital.csv
Для каждой из возможных услуг найдите больницу, в которой эта услуга является самой дешёвой. Результат представьте в виде списка. Помимо названия больницы, укажите штат, округ и город в котором эта больница расположена.
22. Используйте файл Payment_and_value_of_Care-Hospital.csv
Напишите функцию, которая на вход принимает название города и название медицинской процедуры/заболевания. На выход функция должна выдавать список из трех больниц, в которых средняя стоимость указанной услуги является наименьшей по городу, по округу и по штату. Для каждой больницы должна быть указана максимальная и минимальная стоимость услуги.
23. Используйте файл Payment_and_value_of_Care-Hospital.csv
Напишите функцию, которая на вход принимает название города, округа или штата, а на выход выдает количество больниц в нем и процент больниц, в которых есть служба экстренной медицинской помощи. Если значение переданное на вход функции не является городом, округом или штатом, то должно функция должна выдавать соответствующее сообщение об ошибке. Обратите внимание, что функция должна принимать на вход только одно значение.
24. Используйте файл Payment_and_value_of_Care-Hospital.csv
На основе имеющихся данных создайте dataframe, агрегирующий информацию о количестве больниц в городах США. Dataframe должен содержать 5 колонок: название штата, название округа, название города, количество больниц в этом городе и количество больниц в которых осуществляется экстренная медицинская помощь.
25. Используйте файл Payment_and_value_of_Care-Hospital.csv
Напишите функцию, которая на вход принимает название города, а на выход выдает именованный список длины 4, в который записаны название города, названия округа и штата в котором этот город расположен, количество больниц в этом городе, в которых осуществляется экстренная медицинская помощь. Названия элементов списка должны быть ‘City’, ‘Country’, ‘State’ и ‘Hospitals with Emergency Services’.
26. Используйте файл Payment_and_value_of_Care-Hospital.csv
Напишите функцию, которая на вход принимает название города, округа или штата, а на выход выдает количество больниц в нем, процент детских больниц и процент психиатрических больниц. Если значение переданное на вход функции не является городом, округом или штатом, то должно функция должна выдавать соответствующее сообщение об ошибке. Обратите внимание, что функция должна принимать на вход только одно значение.
27. Используйте файл Payment_and_value_of_Care-Hospital.csv
На основе имеющихся данных создайте dataframe, агрегирующий информацию о количестве детских больниц в городах США. Dataframe должен содержать 5 колонок: название штата, название округа, название города, количество детских больниц в этом городе и количество детских больниц в которых осуществляется экстренная медицинская помощь.


***Данные***

_ExpImp.Rdata_

Файл содержит данные Росстата экспорт/импорт продукции по регионам России (млн долл. США).
Названия строк упорядочены по федеральным округам, так что вначале указывается название федерального округа, а потом названия тех субъектов федерации, которые относятся к этому федеральному округу.

_Outcome-of-care-measure.csv_

Файл содержит статистику смертности от 3х заболеваний – Heart Attack, Heart Failure, Pneumonia – в больницах разных Штатов США.

_Payment_and_value_of_Care-Hospital.csv_
Содержит стоимость лечения заболеваний в больницах США.

_data2.csv, data1.txt_
В файлах содержатся значения фенотипических признаков сортов сои.
Количественные признаки: Height, Protein, Oil, Productivity, GermBMatur.
Качественные признаки: GrowthType, Polegaemost, MaturType.
Идентификаторы сортов: V_1, V_2, …

_RH_T.csv_

Файл содержит данные по температуре, относительной влажности и осадкам в Екатеринбурге за период с 2020 год. (T2M – средняя температура в течение дня).

_Air_flows.txt_

Файл содержит данные о пассажирских перевозках между парами городов за 2005, 2006 год. (тыс. человек).

_Regions.csv_
Файл содержит данные о численности населения в субъектах РФ в разные годы.
