---
title: "tidyverse exercises"
output: html_document
---
Каждому студенту необходимо выполнить 2 задания, такие , что номер_второго_задания = номер_первого_задания + 5

_trades.RData_
Файл содержит данные Евростата о импорте и экспорте товаров партнеров Евросоюза (значения указаны в Евро).

1. _trades.RData_ Объедините таблицы в одну, уберите столбец с территорией торговли, т.к. там только Евросоюз, оставим только строки с экспортом и импортом, вынесете данные по экспорту и импорту в отдельные переменные. Отобразите структуру экспорта продукции из Евросоюза по ведущим партнерам в виде столбчатой диаграммы. Обозначьте разные группы экспортируемых товаров разными цветами. Для каждого партера подпишите значение экспорта. Для каждого партнера подпишите какова доля (процент) каждой из групп экспортируемых товаров в общем экспорте. Отрегулируйте местоположение подписей так, чтобы рисунок был максимально наглядным. Придумайте новые названия графика и осей.
2. _trades.RData_ Объедините таблицы в одну, уберите столбец с территорией торговли, т.к. там только Евросоюз, оставим только строки с экспортом и импортом, вынесете данные по экспорту и импорту в отдельные переменные. Постройте линейный график изменения экспорта по годам обозначив разные группы экспортируемых товаров разным цветом. Подпишите значения на графике. Отрегулируйте местоположение подписей так, чтобы рисунок был максимально наглядным. Придумайте новые названия графика и осей.
3. _trades.RData_ Объедините таблицы в одну, уберите столбец с территорией торговли, т.к. там только Евросоюз, оставим только строки с экспортом и импортом, вынесете данные по экспорту и импорту в отдельные переменные. Постройте линейный график изменения экспорта по годам просуммировав разные группы экспортируемых товаров. Подпишите значения на графике. Для минимального значения сделайте подпись красным цветом. Отрегулируйте местоположение подписей так, чтобы рисунок был максимально наглядным. Придумайте новые названия графика и осей.
4. _trades.RData_ Объедините таблицы в одну, уберите столбец с территорией торговли, т.к. там только Евросоюз, оставим только строки с экспортом и импортом, вынесете данные по экспорту и импорту в отдельные переменные. Постройте линейный график изменения суммарных величин импорта и экспорта по импорту/экспорту продуктов питания, напитков и табака (у вас должно получиться 2 графика на одном изображении). Используйте цвет для разделения графиков. Добавьте текстовые подписи величин импорта и экспорта. Отрегулируйте местоположение и размер шрифта для подписей так, чтобы они не налезали на линии и не перекрывали друг друга, рисунок был максимально наглядным. Придумайте новые названия для графика и осей.
5. _trades.RData_ Объедините таблицы в одну, уберите столбец с территорией торговли, т.к. там только Евросоюз, оставим только строки с экспортом и импортом, вынесете данные по экспорту и импорту в отдельные переменные. Отобразите структуру экспорта продукции из Евросоюза по ведущим партнерам в виде круговых диаграммы на одном рисунке. Обозначьте разные группы экспортируемых товаров разными цветами. Для каждого партера подпишите значение экспорта. Для каждого партнера подпишите какова доля (процент) каждой из групп экспортируемых товаров в общем экспорте. Отрегулируйте местоположение подписей так, чтобы рисунок был максимально наглядным. Придумайте новые названия графика и осей.

_ExpImp.Rdata_
Файл содержит данные Росстата экспорт/импорт продукции по регионам России (млн долл. США). Названия строк упорядочены по федеральным округам, так что вначале указывается название федерального округа, а потом названия тех субъектов федерации, которые относятся к этому федеральному округу.

6. _ExpImp.Rdata_ Приведите данные к формату tidydata. Отобразите значения суммарного экспорта и импорта по регионам в виде столбчатой диаграммы [сгруппировав значения по названию региона]. Экспорт и импорт обозначьте разными цветами. Сделайте второй график, на котором значения экспорта и импорта расположите по разные стороны относительно оси x. Подпишите величины экспорта и импорта.
7. _ExpImp.Rdata_ Приведите данные к формату tidydata. Отобразите суммарные значения экспорта и импорта по субъектам федерации, находящимся в Центральном федеральном округе, в виде столбчатой диаграммы [сгруппировав значения по названию субъекта федерации]. Экспорт и импорт обозначьте разными цветами. Сделайте второй график, наложив столбцы экспорта и импорта один на другой и подписав значения разниц между экспортом и ипортом.

8. _ExpImp.Rdata_ Приведите данные к формату tidydata. Отобразите значения суммарного экспорта и импорта металлургической промышленности по регионам в виде столбчатой диаграммы [сгруппировав значения по названию региона]. Подпишите группы товаров, экспорт и импорт обозначьте разными цветами. Сделайте второй график, на котором значения экспорта и импорта расположите по разные стороны относительно оси x. Подпишите значения экспорта и импорта и долю, которую экспорт и импорт металлургической промышленности сотавляет в суммарном импорте и экспорте по регионам.

_reforest.csv_ Файл содержит данные о лесовосстановлении (в тысяч га), полученные из регионального ежегодника Росстата за 2017 год. Файл содержит колонку с названием субъекта и еще 8 колонок с данными по годам. В файле есть пропущенные значения.

9. Удалите строки, в которых есть пропущенные значения и приведите данные к формату tidydata. Отобразите динамику лесовосстановления по годам с помощью линейного графика для любого из федеральных округов, обозначив субъекты федерации разными цветами. Подпишите значения на графике. Отрегулируйте местоположение подписей так, чтобы рисунок был максимально наглядным. Придумайте новые назания графика и осей.
10. Удалите строки, в которых есть пропущенные значения и приведите данные к формату tidydata. Отобразите динамику лесовосстановления по годам с помощью линейного графика для любого из федеральных округов, просуммировав значения соотвествующих субъектов федерации. Подпишите значения на графике. Для минимального значения сделайте подпись красным цветом. Отрегулируйте местоположение подписей так, чтобы рисунок был максимально наглядным. Придумайте новые назания графика и осей.
11. На портале открытых данных Тульской области есть данные о распределении площади лесов и запасов древесины по преобладающим породам и группам возраста https://opendata71.ru/opendata/7107096442-stateforestregisterTularegion/table. Скачайте эти данные в виде таблицы CSV и постройте по ним круговую и столбчатую диаграмму для категории Площадь земель, занятых лесными насаждениями (покрытых лесной растительностью), всего. Подберите цвета, попробуйте изменить ориентировку столбцов на горизонтальную, а для круговой диаграммы поменяейте угол поворота. Подпишите значения.

_data2.csv, data1.txt_

В файлах содержатся значения фенотипических признаков сортов сои. Количественные признаки: Height, Protein, Oil, Productivity, GermBMatur. Качественные признаки: GrowthType, Polegaemost, MaturType. Идентификаторы сортов: V_1, V_2, …

12. _data2.csv, data1.txt_ Объедините data.frames по идентификаторам сортов. Исключите те сорта, для которых есть пропущенные значения. Для всех количественных величин нарисовать гистограммы и плотности распределения (на одном рисунке). Выбрать одну количественную и две качественные переменные . Нарисовать столбчатую диаграмму в которой значениям на оси x соответствуют значения одной кач.переменной и значения другой кач. переменной показаны при помощи цвета. Для количественной переменной нарисовать график плотности и гистограмму(в 2 слоя) на одном графике, и boxplot - на другом.
13. _data2.csv, data1.txt_ Объедините data.frames по идентификаторам сортов. Исключите те сорта, для которых есть пропущенные значения. Выбрать одну количественную и две качественные переменные . Разбить значения количественной переменной на группы в соответствии со значениями одной из качественных переменных. Нарисовать график, на котором отображены плотности распределений и гистограммы для получившихся групп, обозначить разные группы разными цветами.
14. _data2.csv, data1.txt_ Объедините data.frames по идентификаторам сортов. Исключите те сорта, для которых есть пропущенные значения. Для всех наблюдаемых величин из файла test_data1.txt (из первого дз), в которых содержится не более 80% пропущенных значений нарисовать гистограммы. Найтите корреляции Пирсона для количественных переменных. Постройте тепловую карту (heatmap).
